# Created with GitHubActions version 0.2.5
name: CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  - pull_request
  - push
jobs:
  linux:
    name: Test on Ubuntu (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        elixir:
          - '1.13.4'
          - '1.14.2'
        otp:
          - '22.3'
          - '23.3'
          - '24.3'
          - '25.1'
        exclude:
          - elixir: '1.14.2'
            otp: '22.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps
        uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Restore _build
        uses: actions/cache@v3
        with:
          path: _build
          key: _build-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Restore test/support/plts
        uses: actions/cache@v3
        with:
          path: test/support/plts
          key: test/support/plts-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
      - name: Get dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: MIX_ENV=test mix deps.compile
      - name: Compile project
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Check unused dependencies
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
        run: mix deps.unlock --check-unused
      - name: Check code format
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
        run: mix format --check-formatted
      - name: Lint code
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
        run: mix credo --strict
      - name: Run tests
        run: mix test
        if: ${{ !(contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1')) }}
      - name: Run tests with coverage
        run: mix coveralls.github
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
      - name: Static code analysis
        run: mix dialyzer
        if: ${{ contains(matrix.elixir, '1.14.2') && contains(matrix.otp, '25.1') }}
